apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: consoledot-health-metrics
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: consoledot-health-metrics
    name: consoledot-health-metrics
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        app: consoledot-health-metrics
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: consoledot-health-metrics
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - consoledot-health-metrics
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - consoledot-health-metrics
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers: 
        - env:
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_SERVICE_NAME
              value: POSTGRES_SQL
            - name: DATABASE_ENGINE
              value: postgresql
            - name: DATABASE_NAME
              value: ${DB_SECRET_NAME}
            - name: POSTGRES_SQL_SERVICE_HOST
              value: metrics-db
            - name: POSTGRES_SQL_SERVICE_PORT
              value: '5432'
            - name: DATABASE_USER
              value: ${DB_SECRET_NAME}
            - name: DATABASE_PASSWORD
              value: ${DB_SECRET_NAME}
            - name: PROMETHEUS_AUTH_TOKEN
              value: 
            - name: DEPLOYMENT_DB_HOST
              value: deploy-events-db.cgkhgcepvyrh.us-east-1.rds.amazonaws.com
            - name: DEPLOYMENT_DB_NAME
              value: postgres
            - name: DEPLOYMENT_DB_USER
              value: postgres
            - name: DEPLOYMENT_DB_PASSWORD
              value:
          name: metric-scraper
          image: quay.io/rh_ee_maholder/consoledot-health-metrics:latest
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /config
            name: config-vol
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            name: consoledot-health-metrics-config
          name: config-vol
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: consoledot-health-metrics
    name: consoledot-health-metrics
  spec:
    ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
    - name: 8080-tcp
      port: 8080
      protocol: TCP
    selector:
      app: consoledot-health-metrics
    sessionAffinity: None
    type: ClusterIP 
  status:
    loadBalancer: {}
parameters:
- description: The number of replicas to use in the deployment
  name: REPLICAS
  value: '1'
- description: Volume space available for data, e.g. 512Mi, 2Gi
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: Initial amount of memory
  displayName: Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 512Mi
- description: Maximum amount of memory
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 1Gi
- description: Initial amount of cpu
  displayName: CPU Request
  name: CPU_REQUEST
  required: true
  value: 300m
- description: Maximum amount of cpu
  displayName: CPU Limit
  name: CPU_LIMIT
  required: true
  value: '1'
- description: Name of DB secret
  name: DB_SECRET_NAME
  value: metrics-db